name: Deploy Devops TP2 to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Hadolint
      run: |
        ls
        pwd
        docker run --rm -i hadolint/hadolint < ./Dockerfile
    - name: Build Docker image
      run: docker build -t dzung17/devops-tp2:0.0.1 .
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker push dzung17/devops-tp2:0.0.1
